-- Add buy_price and mrp_price columns
ALTER TABLE items
  ADD COLUMN IF NOT EXISTS buy_price DOUBLE PRECISION DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS mrp_price DOUBLE PRECISION DEFAULT 0 NOT NULL;

ALTER TABLE invoice_details
  ADD COLUMN IF NOT EXISTS buy_price DOUBLE PRECISION DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS mrp_price DOUBLE PRECISION DEFAULT 0 NOT NULL;

ALTER TABLE invoice_archive_details
  ADD COLUMN IF NOT EXISTS buy_price DOUBLE PRECISION DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS mrp_price DOUBLE PRECISION DEFAULT 0 NOT NULL;
