"""
mail_scheduler_service.py

Background daemon thread that checks active mail schedulers every minute.
When the current HH:MM matches a scheduler's send_time, it generates a
styled Excel (.xlsx) report and sends it as an email attachment.

Uses the same SMTP credentials as support_chat.py (SUPPORT_SENDER_EMAIL etc.)
"""
import io
import logging
import os
import smtplib
import threading
import time
from datetime import datetime, timedelta
from email.message import EmailMessage

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from app.db import SessionLocal
from app.models.mail_scheduler import MailScheduler

logger = logging.getLogger(__name__)

SENDER_EMAIL    = (os.getenv("SUPPORT_SENDER_EMAIL") or "").strip()
SENDER_PASSWORD = (os.getenv("SUPPORT_SENDER_PASSWORD") or "").strip()
SMTP_HOST       = (os.getenv("SUPPORT_SMTP_HOST") or "smtp.gmail.com").strip()
SMTP_PORT       = int((os.getenv("SUPPORT_SMTP_PORT") or "465").strip())

_last_sent: dict[int, str] = {}

REPORT_LABELS = {
    "daily_sales": "Daily Sales Summary",
    "item_sales":  "Item-Wise Sales",
    "gst_summary": "GST Summary",
}

# ─── Excel style helpers ──────────────────────────────────────────────────────

HEADER_FILL  = PatternFill("solid", fgColor="0B3C8C")
ALT_FILL     = PatternFill("solid", fgColor="EEF2FF")
HEADER_FONT  = Font(bold=True, color="FFFFFF", size=10)
TITLE_FONT   = Font(bold=True, size=13, color="0B3C8C")
BODY_FONT    = Font(size=10)
BOLD_FONT    = Font(bold=True, size=10)
CENTER       = Alignment(horizontal="center", vertical="center")
LEFT         = Alignment(horizontal="left",   vertical="center")
RIGHT        = Alignment(horizontal="right",  vertical="center")
THIN_BORDER  = Border(
    left=Side(style="thin", color="D1D5DB"),
    right=Side(style="thin", color="D1D5DB"),
    top=Side(style="thin", color="D1D5DB"),
    bottom=Side(style="thin", color="D1D5DB"),
)


def _style_header_row(ws, row_num: int, col_count: int):
    for col in range(1, col_count + 1):
        cell = ws.cell(row=row_num, column=col)
        cell.fill   = HEADER_FILL
        cell.font   = HEADER_FONT
        cell.alignment = CENTER
        cell.border = THIN_BORDER


def _style_data_row(ws, row_num: int, col_count: int, alternate: bool):
    fill = ALT_FILL if alternate else PatternFill("solid", fgColor="FFFFFF")
    for col in range(1, col_count + 1):
        cell = ws.cell(row=row_num, column=col)
        cell.fill      = fill
        cell.font      = BODY_FONT
        cell.border    = THIN_BORDER
        cell.alignment = RIGHT if col > 2 else LEFT


def _auto_width(ws):
    for col_cells in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col_cells[0].column)
        for cell in col_cells:
            try:
                if cell.value:
                    max_len = max(max_len, len(str(cell.value)))
            except Exception:
                pass
        ws.column_dimensions[col_letter].width = min(max(max_len + 4, 12), 40)


def _write_title(ws, title: str, date_str: str, col_count: int):
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=col_count)
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=col_count)
    ws["A1"].value     = title
    ws["A1"].font      = TITLE_FONT
    ws["A1"].alignment = CENTER
    ws["A2"].value     = f"Date: {date_str}  |  Generated by Haappii Billing"
    ws["A2"].font      = Font(size=9, color="6B7280", italic=True)
    ws["A2"].alignment = CENTER
    ws.row_dimensions[1].height = 22
    ws.row_dimensions[2].height = 16


# ─── Yesterday ───────────────────────────────────────────────────────────────

def _yesterday():
    return (datetime.now() - timedelta(days=1)).date()


# ─── Report generators (return xlsx bytes) ───────────────────────────────────

def _generate_daily_sales_xlsx(db, shop_id: int) -> bytes:
    from sqlalchemy import func
    from app.models.invoice import Invoice
    from app.models.branch import Branch

    d       = _yesterday()
    d_start = datetime.combine(d, datetime.min.time())
    d_end   = datetime.combine(d, datetime.max.time())

    rows = (
        db.query(
            Branch.branch_name.label("branch"),
            func.count(func.distinct(Invoice.invoice_id)).label("bills"),
            func.coalesce(func.sum(Invoice.total_amount), 0).label("gross"),
            func.coalesce(func.sum(Invoice.discounted_amt), 0).label("discount"),
            func.coalesce(func.sum(Invoice.tax_amt), 0).label("tax"),
            func.coalesce(
                func.sum(Invoice.total_amount - func.coalesce(Invoice.discounted_amt, 0)), 0
            ).label("net"),
        )
        .outerjoin(Branch, Branch.branch_id == Invoice.branch_id)
        .filter(Invoice.shop_id == shop_id,
                Invoice.created_time >= d_start,
                Invoice.created_time <= d_end)
        .group_by(Branch.branch_name)
        .all()
    )

    headers = ["Date", "Branch", "Bills", "Gross Amount (₹)", "Discount (₹)", "Tax / GST (₹)", "Net Amount (₹)"]
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Daily Sales"
    ws.freeze_panes = "A4"

    _write_title(ws, "Daily Sales Summary", str(d), len(headers))
    _style_header_row(ws, 3, len(headers))
    for i, h in enumerate(headers, 1):
        ws.cell(row=3, column=i).value = h

    totals = [0, 0, 0, 0, 0]
    for idx, r in enumerate(rows, 4):
        data = [str(d), r.branch or "—", r.bills,
                round(float(r.gross), 2), round(float(r.discount), 2),
                round(float(r.tax), 2),  round(float(r.net), 2)]
        for col, val in enumerate(data, 1):
            ws.cell(row=idx, column=col).value = val
        _style_data_row(ws, idx, len(headers), idx % 2 == 0)
        totals[0] += r.bills
        totals[1] += float(r.gross)
        totals[2] += float(r.discount)
        totals[3] += float(r.tax)
        totals[4] += float(r.net)

    # Totals row
    total_row = len(rows) + 4
    totals_data = ["", "TOTAL", totals[0],
                   round(totals[1], 2), round(totals[2], 2),
                   round(totals[3], 2), round(totals[4], 2)]
    for col, val in enumerate(totals_data, 1):
        cell = ws.cell(row=total_row, column=col)
        cell.value     = val
        cell.font      = BOLD_FONT
        cell.fill      = PatternFill("solid", fgColor="DBEAFE")
        cell.border    = THIN_BORDER
        cell.alignment = RIGHT if col > 2 else LEFT

    _auto_width(ws)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def _generate_item_sales_xlsx(db, shop_id: int) -> bytes:
    from sqlalchemy import func
    from app.models.invoice import Invoice
    from app.models.invoice_details import InvoiceDetail
    from app.models.items import Item
    from app.models.branch import Branch

    d       = _yesterday()
    d_start = datetime.combine(d, datetime.min.time())
    d_end   = datetime.combine(d, datetime.max.time())

    rows = (
        db.query(
            Item.item_name.label("item"),
            Branch.branch_name.label("branch"),
            func.sum(InvoiceDetail.quantity).label("qty"),
            func.coalesce(func.sum(InvoiceDetail.amount), 0).label("amount"),
        )
        .join(InvoiceDetail, InvoiceDetail.item_id == Item.item_id)
        .join(Invoice, Invoice.invoice_id == InvoiceDetail.invoice_id)
        .outerjoin(Branch, Branch.branch_id == Invoice.branch_id)
        .filter(Invoice.shop_id == shop_id,
                Invoice.created_time >= d_start,
                Invoice.created_time <= d_end)
        .group_by(Item.item_name, Branch.branch_name)
        .order_by(func.sum(InvoiceDetail.amount).desc())
        .all()
    )

    headers = ["Date", "Item", "Branch", "Quantity", "Amount (₹)"]
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Item Sales"
    ws.freeze_panes = "A4"

    _write_title(ws, "Item-Wise Sales", str(d), len(headers))
    _style_header_row(ws, 3, len(headers))
    for i, h in enumerate(headers, 1):
        ws.cell(row=3, column=i).value = h

    total_qty, total_amt = 0, 0.0
    for idx, r in enumerate(rows, 4):
        data = [str(d), r.item, r.branch or "—",
                int(r.qty or 0), round(float(r.amount or 0), 2)]
        for col, val in enumerate(data, 1):
            ws.cell(row=idx, column=col).value = val
        _style_data_row(ws, idx, len(headers), idx % 2 == 0)
        total_qty += int(r.qty or 0)
        total_amt += float(r.amount or 0)

    total_row = len(rows) + 4
    totals_data = ["", "TOTAL", "", total_qty, round(total_amt, 2)]
    for col, val in enumerate(totals_data, 1):
        cell = ws.cell(row=total_row, column=col)
        cell.value     = val
        cell.font      = BOLD_FONT
        cell.fill      = PatternFill("solid", fgColor="DBEAFE")
        cell.border    = THIN_BORDER
        cell.alignment = RIGHT if col > 2 else LEFT

    _auto_width(ws)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def _generate_gst_xlsx(db, shop_id: int) -> bytes:
    from sqlalchemy import func
    from app.models.invoice import Invoice

    d       = _yesterday()
    d_start = datetime.combine(d, datetime.min.time())
    d_end   = datetime.combine(d, datetime.max.time())

    row = (
        db.query(
            func.count(func.distinct(Invoice.invoice_id)).label("invoices"),
            func.coalesce(func.sum(Invoice.total_amount), 0).label("gross"),
            func.coalesce(func.sum(Invoice.tax_amt), 0).label("tax"),
            func.coalesce(func.sum(Invoice.discounted_amt), 0).label("discount"),
            func.coalesce(
                func.sum(Invoice.total_amount - func.coalesce(Invoice.discounted_amt, 0)), 0
            ).label("net"),
        )
        .filter(Invoice.shop_id == shop_id,
                Invoice.created_time >= d_start,
                Invoice.created_time <= d_end)
        .first()
    )

    headers = ["Date", "Total Invoices", "Gross Amount (₹)", "Total Tax / GST (₹)", "Discount (₹)", "Net Payable (₹)"]
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "GST Summary"
    ws.freeze_panes = "A4"

    _write_title(ws, "GST Summary", str(d), len(headers))
    _style_header_row(ws, 3, len(headers))
    for i, h in enumerate(headers, 1):
        ws.cell(row=3, column=i).value = h

    if row:
        data = [str(d), row.invoices,
                round(float(row.gross), 2),   round(float(row.tax), 2),
                round(float(row.discount), 2), round(float(row.net), 2)]
        for col, val in enumerate(data, 1):
            ws.cell(row=4, column=col).value = val
        _style_data_row(ws, 4, len(headers), False)

    _auto_width(ws)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


GENERATORS = {
    "daily_sales": _generate_daily_sales_xlsx,
    "item_sales":  _generate_item_sales_xlsx,
    "gst_summary": _generate_gst_xlsx,
}


# ─── Email sender ─────────────────────────────────────────────────────────────

def _send_report_email(recipient: str, subject: str, xlsx_bytes: bytes, filename: str):
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"]    = SENDER_EMAIL
    msg["To"]      = recipient
    msg.set_content(
        f"Hi,\n\nPlease find the attached report: {subject}\n\n"
        f"This is an automated report from Haappii Billing.\n"
    )
    msg.add_attachment(
        xlsx_bytes,
        maintype="application",
        subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        filename=filename,
    )
    with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as smtp:
        smtp.login(SENDER_EMAIL, SENDER_PASSWORD)
        smtp.send_message(msg)


# ─── Scheduler tick ───────────────────────────────────────────────────────────

def _run_due_schedulers():
    now_hhmm  = datetime.now().strftime("%H:%M")
    today_str = datetime.now().strftime("%Y-%m-%d")

    if not (SENDER_EMAIL and SENDER_PASSWORD):
        return

    db = SessionLocal()
    try:
        due = db.query(MailScheduler).filter(
            MailScheduler.is_active == True,
            MailScheduler.send_time == now_hhmm,
        ).all()

        for sched in due:
            guard = f"{sched.id}:{today_str}:{now_hhmm}"
            if _last_sent.get(sched.id) == guard:
                continue

            gen = GENERATORS.get(sched.report_type)
            if not gen:
                logger.warning("Unknown report_type '%s' for scheduler %d", sched.report_type, sched.id)
                continue

            try:
                xlsx_bytes = gen(db, sched.shop_id)
                label      = REPORT_LABELS.get(sched.report_type, sched.report_type)
                date_str   = str(_yesterday())
                subject    = f"{sched.name} — {label} ({date_str})"
                filename   = f"{sched.report_type}_{date_str}.xlsx"
                _send_report_email(sched.recipient_email, subject, xlsx_bytes, filename)
                _last_sent[sched.id] = guard
                logger.info("Mail scheduler %d sent report to %s", sched.id, sched.recipient_email)
            except Exception:
                logger.exception("Mail scheduler %d failed to send", sched.id)
    finally:
        db.close()


# ─── Background thread ────────────────────────────────────────────────────────

def _scheduler_loop():
    while True:
        try:
            _run_due_schedulers()
        except Exception:
            logger.exception("Mail scheduler loop error")
        time.sleep(60)


def start_mail_scheduler():
    """Start the background daemon thread. Call once from app startup."""
    t = threading.Thread(target=_scheduler_loop, daemon=True, name="mail-report-scheduler")
    t.start()
    logger.info("Mail report scheduler thread started")
